server:
  port: 9990
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/CreditCardSimulator
    username: root
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
        hibernate.format_sql: true
       
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
   
      
logging:
  group:
    jackson: com.fasterxml
    dev: com.own
  file:
    file: /home/local/NPST/radhe.shyam/Radhey/works/logs/my.log
    
file: 
  upload-dir: /home/local/NPST/radhe.shyam/Radhey/works/upload/
swagger:
  api-version: 1.0
  deep-linking: true
  default-model-expand-depth: 1
  default-models-expand-depth: 1
  description: Swagger-UI projects
  display-request-duration: false
  enable-url-templating: true
  enabled: true
  display-operation-id:  true
  filter: true
  show-extensions: true
  max-displayed-tags: 0
  title: Swagger-api 
  use-default-response-messages: true
  
user:
  country: CountryName
  
